In [12]:
import pandas as pd

df = pd.read_csv('RewardsData.csv')

df.head(20)

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,Tags
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,12/16/2021 17:42,ClassOf2025
1,2,NaN,Los Angeles,Colorado,90210,320,320,0,8/19/2020 11:15,4/13/2022 14:28,ClassOf2025|apple
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,4/21/2021 10:54,Freshman|Developer
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,6/30/2022 22:22,GraduateStudent|admin|MBBvsDuke
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,12/30/2020 10:57,Student|NOBSBvsNDGame3|NOBSBvsNDGame3A
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,6/8/2022 23:55,GraduateStudent|admin
6,7,9/22/1995,NaN,NaN,NaN,570,570,0,8/21/2020 10:23,4/27/2022 16:27,ClassOf2025
7,8,NaN,NaN,NaN,NaN,2410,2410,0,8/22/2020 13:53,3/31/2022 1:56,ClassOf2022|21DZ
8,9,NaN,NaN,NaN,NaN,2895,3195,300,8/22/2020 14:03,10/10/2021 16:05,Student|Senior|DriveInNCSU|ClassificationPts|1...
9,10,7/20/1999,Winston Salem,NC,27106,8465,8515,50,8/22/2020 14:42,4/9/2022 14:10,GraduateStudent
10,11,7/22/2000,NaN,NaN,NaN,22210,22210,0,8/22/2020 15:59,6/21/2022 19:32,ClassOf2022
11,12,NaN,NaN,NaN,NaN,1355,4355,3000,8/22/2020 17:37,5/18/2021 20:57,Student|Senior|DriveInNCSU|ClassificationPts|1...
12,13,NaN,NaN,NaN,NaN,3290,3290,0,8/22/2020 18:20,4/10/2022 23:04,Student|Senior|ClassificationPts|CampbellGroup...
13,14,11/1/2000,Winston-Salem,NC,27106,10965,17165,6200,8/22/2020 20:02,5/11/2022 15:16,ClassOf2023|MBBvsDuke
14,15,6/27/2000,Thomasville,NC,27360,5750,5750,0,8/23/2020 9:26,4/11/2022 16:27,ClassOf2022
15,16,4/24/1999,NaN,NaN,NaN,4310,4610,300,8/23/2020 23:43,8/27/2021 13:01,Student|Senior|ClassificationPts|BSBvNDGame1|B...
16,17,NaN,NaN,NaN,NaN,890,890,0,8/24/2020 11:30,1/23/2022 23:28,ClassOf2022
17,18,7/5/1998,NaN,NaN,NaN,550,550,0,8/24/2020 14:48,10/26/2020 10:01,NOBSBvsNDGame3|NOBSBvsNDGame3A
18,19,NaN,Goldsboro,North Carolina,27534,3425,3425,0,8/24/2020 15:35,6/30/2022 21:19,ClassOf2023|21EPI|MBBvsDuke
19,20,NaN,NaN,NaN,NaN,800,800,0,8/24/2020 18:23,NaN,Student|19RetroactivePoints|NOBSBvsNDGame3|NOB...

In [15]:
df.isna()

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,Tags
0,False,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
7247,False,True,True,True,True,False,False,False,False,False,False
7248,False,True,True,True,True,False,False,False,False,False,False
7249,False,False,True,True,True,False,False,False,False,False,False
7250,False,True,True,True,True,False,False,False,False,False,False
7251,False,True,True,True,True,False,False,False,False,False,False

In [20]:
missing_value_count = df.isna().sum()
missing_value_count

User ID                   0
Birthdate              6080
City                   6922
State                  6922
Zip                    6922
Available Points          0
Total Points Earned       0
Points Spent              0
Joined On                 0
Last Seen                 0
Tags                      0
dtype: int64

In [17]:
missing_values_percent = missing_value_count/len(df) * 100
missing_values_percent

User ID                 0.000000
Birthdate              83.838941
City                   95.449531
State                  95.449531
Zip                    95.449531
Available Points        0.000000
Total Points Earned     0.000000
Points Spent            0.000000
Joined On               0.000000
Last Seen               0.000000
Tags                    0.000000
dtype: float64

In [7]:
df['Last Seen']

0       12/16/2021 17:42
1        4/13/2022 14:28
2        4/21/2021 10:54
3        6/30/2022 22:22
4       12/30/2020 10:57
              ...
7247     6/30/2022 12:04
7248     6/28/2022 22:43
7249     6/30/2022 12:48
7250     6/30/2022 20:39
7251       7/1/2022 2:42
Name: Last Seen, Length: 7252, dtype: str

In [8]:
df['Last Seen'] = pd.to_datetime(df['Last Seen'])

In [9]:
df['Last Seen']

0      2021-12-16 17:42:00
1      2022-04-13 14:28:00
2      2021-04-21 10:54:00
3      2022-06-30 22:22:00
4      2020-12-30 10:57:00
               ...
7247   2022-06-30 12:04:00
7248   2022-06-28 22:43:00
7249   2022-06-30 12:48:00
7250   2022-06-30 20:39:00
7251   2022-07-01 02:42:00
Name: Last Seen, Length: 7252, dtype: datetime64[us]

In [10]:
df['Last Seen'].max()

Timestamp('2022-07-01 08:36:00')

In [11]:
df['Last Seen'].min()

Timestamp('2020-10-12 14:38:00')

In [14]:
df['Last Seen'] = df['Last Seen'].fillna(value=df['Last Seen'].min())

In [58]:
df_sample = df.dropna()
df_sample

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,Tags
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,12/16/2021 17:42,ClassOf2025
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,4/21/2021 10:54,Freshman|Developer
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,6/30/2022 22:22,GraduateStudent|admin|MBBvsDuke
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,12/30/2020 10:57,Student|NOBSBvsNDGame3|NOBSBvsNDGame3A
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,6/8/2022 23:55,GraduateStudent|admin
...,...,...,...,...,...,...,...,...,...,...,...
7228,7219,6/12/2004,Lutherville,Maryland,21093,490,490,0,6/22/2022 17:28,6/30/2022 8:43,Student|ClassOf2026
7229,7220,8/7/1999,Winston-Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,6/26/2022 16:39,Student|ClassOf2023
7236,7227,3/14/2000,Clemmons,North Carolina,27012,460,460,0,6/23/2022 22:18,6/29/2022 23:40,Student|GraduateStudent
7239,7230,5/18/1999,Winston Salem,North Carolina,27107,410,410,0,6/24/2022 16:03,6/24/2022 16:06,Student|GraduateStudent
7244,7235,6/20/2004,Guaynabo,Puerto Rico,969,440,440,0,6/27/2022 10:21,7/1/2022 8:36,Student|ClassOf2026

In [52]:
df_sample.isna().sum()

User ID                0
Birthdate              0
City                   0
State                  0
Zip                    0
Available Points       0
Total Points Earned    0
Points Spent           0
Joined On              0
Last Seen              0
Tags                   0
dtype: int64

In [59]:
df_sample = df_sample.drop('Tags',axis=1)
df_sample

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,12/16/2021 17:42
2,3,1/11/1990,Merida,AL,97204,330,330,0,10/13/2020 16:20,4/21/2021 10:54
3,4,4/16/1990,Winston-Salem,NC,27106,10790,14290,3500,8/18/2020 13:21,6/30/2022 22:22
4,5,3/24/1994,Winston-Salem,NC,27109,650,650,0,8/21/2020 11:27,12/30/2020 10:57
5,6,10/9/1995,G,AL,85588,7085,7395,310,8/18/2020 14:28,6/8/2022 23:55
...,...,...,...,...,...,...,...,...,...,...
7228,7219,6/12/2004,Lutherville,Maryland,21093,490,490,0,6/22/2022 17:28,6/30/2022 8:43
7229,7220,8/7/1999,Winston-Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,6/26/2022 16:39
7236,7227,3/14/2000,Clemmons,North Carolina,27012,460,460,0,6/23/2022 22:18,6/29/2022 23:40
7239,7230,5/18/1999,Winston Salem,North Carolina,27107,410,410,0,6/24/2022 16:03,6/24/2022 16:06
7244,7235,6/20/2004,Guaynabo,Puerto Rico,969,440,440,0,6/27/2022 10:21,7/1/2022 8:36

In [57]:
df_sample['State'] = df_sample['State'].replace(us_state_abbrev)

0           Georgia
2                AL
3                NC
4               NaN
5               NaN
           ...
7228            NaN
7229            NaN
7236            NaN
7239            NaN
7244    Puerto Rico
Name: State, Length: 172, dtype: str

In [33]:
df_unique_state = pd.DataFrame(df_unique_state, columns=['State'])

df_unique_state['State'] = df_unique_state['State'].replace(to_replace=['Puerto Rico'],value='PR')

df_unique_state['State'] = df_unique_state['State'].str.strip()

df_unique_state['State'] = df_unique_state['State'].str.title()

df_unique_state['State']

0                       Al
1                       Ct
2               California
3                 Colorado
4              Connecticut
5     District Of Columbia
6                       Fl
7                  Florida
8                       Ga
9                  Georgia
10                Illinois
11                Kentucky
12                      Ma
13                      Md
14                      Mn
15                Maryland
16           Massachusetts
17                      Nc
18                      Nj
19                      Ny
20              New Jersey
21              New Mexico
22                New York
23          North Carolina
24                      Oh
25                    Ohio
26                      Pa
27            Pennsylvania
28                      Pr
29                      Sc
30                      Tn
31                      Tx
32               Tennessee
33                   Texas
34                      Wi
Name: State, dtype: str

In [38]:
us_state_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "Puerto Rico": "PR",
    "District Of Columbia" : "DOC"
}

In [60]:
state_full_name = {v: k for k, v in us_state_abbrev.items()}

df_sample['State'] = df_sample['State'].replace(state_full_name)

df_sample['State']

0              Georgia
2              Alabama
3       North Carolina
4       North Carolina
5              Alabama
             ...
7228          Maryland
7229    North Carolina
7236    North Carolina
7239    North Carolina
7244       Puerto Rico
Name: State, Length: 172, dtype: str

In [40]:
df_unique_state['State']

0      Al
1      Ct
2      CA
3      CO
4      CT
5     DOC
6      Fl
7      FL
8      Ga
9      GA
10     IL
11     KY
12     Ma
13     Md
14     Mn
15     MD
16     MA
17     Nc
18     Nj
19     Ny
20     NJ
21     NM
22     NY
23     NC
24     Oh
25     OH
26     Pa
27     PA
28     Pr
29     Sc
30     Tn
31     Tx
32     TN
33     TX
34     Wi
Name: State, dtype: str

In [44]:
us_state_abbrev.items()

states_df = pd.DataFrame(list(us_state_abbrev.items()), columns=['State','State_ABBREV'])

states_df

                   State State_ABBREV
0                Alabama           AL
1                 Alaska           AK
2                Arizona           AZ
3               Arkansas           AR
4             California           CA
5               Colorado           CO
6            Connecticut           CT
7               Delaware           DE
8                Florida           FL
9                Georgia           GA
10                Hawaii           HI
11                 Idaho           ID
12              Illinois           IL
13               Indiana           IN
14                  Iowa           IA
15                Kansas           KS
16              Kentucky           KY
17             Louisiana           LA
18                 Maine           ME
19              Maryland           MD
20         Massachusetts           MA
21              Michigan           MI
22             Minnesota           MN
23           Mississippi           MS
24              Missouri           MO
25               Montana           MT
26              Nebraska           NE
27                Nevada           NV
28         New Hampshire           NH
29            New Jersey           NJ
30            New Mexico           NM
31              New York           NY
32        North Carolina           NC
33          North Dakota           ND
34                  Ohio           OH
35              Oklahoma           OK
36                Oregon           OR
37          Pennsylvania           PA
38          Rhode Island           RI
39        South Carolina           SC
40          South Dakota           SD
41             Tennessee           TN
42                 Texas           TX
43                  Utah           UT
44               Vermont           VT
45              Virginia           VA
46            Washington           WA
47         West Virginia           WV
48             Wisconsin           WI
49               Wyoming           WY
50  District of Columbia           DC
51           Puerto Rico           PR
52  District Of Columbia          DOC

In [43]:
list(us_state_abbrev.items())

[('Alabama', 'AL'),
 ('Alaska', 'AK'),
 ('Arizona', 'AZ'),
 ('Arkansas', 'AR'),
 ('California', 'CA'),
 ('Colorado', 'CO'),
 ('Connecticut', 'CT'),
 ('Delaware', 'DE'),
 ('Florida', 'FL'),
 ('Georgia', 'GA'),
 ('Hawaii', 'HI'),
 ('Idaho', 'ID'),
 ('Illinois', 'IL'),
 ('Indiana', 'IN'),
 ('Iowa', 'IA'),
 ('Kansas', 'KS'),
 ('Kentucky', 'KY'),
 ('Louisiana', 'LA'),
 ('Maine', 'ME'),
 ('Maryland', 'MD'),
 ('Massachusetts', 'MA'),
 ('Michigan', 'MI'),
 ('Minnesota', 'MN'),
 ('Mississippi', 'MS'),
 ('Missouri', 'MO'),
 ('Montana', 'MT'),
 ('Nebraska', 'NE'),
 ('Nevada', 'NV'),
 ('New Hampshire', 'NH'),
 ('New Jersey', 'NJ'),
 ('New Mexico', 'NM'),
 ('New York', 'NY'),
 ('North Carolina', 'NC'),
 ('North Dakota', 'ND'),
 ('Ohio', 'OH'),
 ('Oklahoma', 'OK'),
 ('Oregon', 'OR'),
 ('Pennsylvania', 'PA'),
 ('Rhode Island', 'RI'),
 ('South Carolina', 'SC'),
 ('South Dakota', 'SD'),
 ('Tennessee', 'TN'),
 ('Texas', 'TX'),
 ('Utah', 'UT'),
 ('Vermont', 'VT'),
 ('Virginia', 'VA'),
 ('Washington', 'WA'),
 ('West Virginia', 'WV'),
 ('Wisconsin', 'WI'),
 ('Wyoming', 'WY'),
 ('District of Columbia', 'DC'),
 ('Puerto Rico', 'PR'),
 ('District Of Columbia', 'DOC')]

In [61]:
df_sample_merged = pd.merge(df_sample, states_df , on="State", how='left' )

df_sample_merged

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,State_ABBREV
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,12/16/2021 17:42,GA
1,3,1/11/1990,Merida,Alabama,97204,330,330,0,10/13/2020 16:20,4/21/2021 10:54,AL
2,4,4/16/1990,Winston-Salem,North Carolina,27106,10790,14290,3500,8/18/2020 13:21,6/30/2022 22:22,NC
3,5,3/24/1994,Winston-Salem,North Carolina,27109,650,650,0,8/21/2020 11:27,12/30/2020 10:57,NC
4,6,10/9/1995,G,Alabama,85588,7085,7395,310,8/18/2020 14:28,6/8/2022 23:55,AL
...,...,...,...,...,...,...,...,...,...,...,...
167,7219,6/12/2004,Lutherville,Maryland,21093,490,490,0,6/22/2022 17:28,6/30/2022 8:43,MD
168,7220,8/7/1999,Winston-Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,6/26/2022 16:39,NC
169,7227,3/14/2000,Clemmons,North Carolina,27012,460,460,0,6/23/2022 22:18,6/29/2022 23:40,NC
170,7230,5/18/1999,Winston Salem,North Carolina,27107,410,410,0,6/24/2022 16:03,6/24/2022 16:06,NC
171,7235,6/20/2004,Guaynabo,Puerto Rico,969,440,440,0,6/27/2022 10:21,7/1/2022 8:36,PR

In [63]:
df_sample_merged.rename(columns={'State_ABBREV':'State_Abbreviation'}, inplace = True)
df_sample_merged

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen,State_Abbreviation
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,12/16/2021 17:42,GA
1,3,1/11/1990,Merida,Alabama,97204,330,330,0,10/13/2020 16:20,4/21/2021 10:54,AL
2,4,4/16/1990,Winston-Salem,North Carolina,27106,10790,14290,3500,8/18/2020 13:21,6/30/2022 22:22,NC
3,5,3/24/1994,Winston-Salem,North Carolina,27109,650,650,0,8/21/2020 11:27,12/30/2020 10:57,NC
4,6,10/9/1995,G,Alabama,85588,7085,7395,310,8/18/2020 14:28,6/8/2022 23:55,AL
...,...,...,...,...,...,...,...,...,...,...,...
167,7219,6/12/2004,Lutherville,Maryland,21093,490,490,0,6/22/2022 17:28,6/30/2022 8:43,MD
168,7220,8/7/1999,Winston-Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,6/26/2022 16:39,NC
169,7227,3/14/2000,Clemmons,North Carolina,27012,460,460,0,6/23/2022 22:18,6/29/2022 23:40,NC
170,7230,5/18/1999,Winston Salem,North Carolina,27107,410,410,0,6/24/2022 16:03,6/24/2022 16:06,NC
171,7235,6/20/2004,Guaynabo,Puerto Rico,969,440,440,0,6/27/2022 10:21,7/1/2022 8:36,PR

In [64]:
state_abbrev_col = df_sample_merged.pop('State_Abbreviation')

df_sample_merged.insert(5, 'State_Abbreviation', state_abbrev_col )

In [66]:
state_abbrev_col = df_sample_merged.pop('State_Abbreviation')

df_sample_merged.insert(4, 'State_Abbreviation', state_abbrev_col ) 

df_sample_merged

,User ID,Birthdate,City,State,State_Abbreviation,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen
0,1,1/31/1992,Minneapolis,Georgia,GA,55401,300,300,0,9/4/2020 0:15,12/16/2021 17:42
1,3,1/11/1990,Merida,Alabama,AL,97204,330,330,0,10/13/2020 16:20,4/21/2021 10:54
2,4,4/16/1990,Winston-Salem,North Carolina,NC,27106,10790,14290,3500,8/18/2020 13:21,6/30/2022 22:22
3,5,3/24/1994,Winston-Salem,North Carolina,NC,27109,650,650,0,8/21/2020 11:27,12/30/2020 10:57
4,6,10/9/1995,G,Alabama,AL,85588,7085,7395,310,8/18/2020 14:28,6/8/2022 23:55
...,...,...,...,...,...,...,...,...,...,...,...
167,7219,6/12/2004,Lutherville,Maryland,MD,21093,490,490,0,6/22/2022 17:28,6/30/2022 8:43
168,7220,8/7/1999,Winston-Salem,North Carolina,NC,27106,430,430,0,6/22/2022 17:36,6/26/2022 16:39
169,7227,3/14/2000,Clemmons,North Carolina,NC,27012,460,460,0,6/23/2022 22:18,6/29/2022 23:40
170,7230,5/18/1999,Winston Salem,North Carolina,NC,27107,410,410,0,6/24/2022 16:03,6/24/2022 16:06
171,7235,6/20/2004,Guaynabo,Puerto Rico,PR,969,440,440,0,6/27/2022 10:21,7/1/2022 8:36

In [67]:
zip_unique_values = sorted(df_sample_merged['Zip'].unique())

zip_unique_values

['10538',
 '11768',
 '11787',
 '13026',
 '13078',
 '13492',
 '13753',
 '14530',
 '15217',
 '19352',
 '19355',
 '19382',
 '1945',
 '2030',
 '2067',
 '20814',
 '21093',
 '22213',
 '2332',
 '2478',
 '2493',
 '2532',
 '2653',
 '27012',
 '27013',
 '27051',
 '27101',
 '27103',
 '27104',
 '27106',
 '27107',
 '27109',
 '27127',
 '27360',
 '27406',
 '27410',
 '27516',
 '27707-1634',
 '28078',
 '28079',
 '28097',
 '28115',
 '28117',
 '28173',
 '28205',
 '28209',
 '28216',
 '28262',
 '28269',
 '28277',
 '28462',
 '28655',
 '29204',
 '29466',
 '30165',
 '30273',
 '30311',
 '30338',
 '32174',
 '32223',
 '32608',
 '33157',
 '33410',
 '33596',
 '33908',
 '37204',
 '37205',
 '38112',
 '40222',
 '45174',
 '45419',
 '53217',
 '55401',
 '55439',
 '60048',
 '60085',
 '60515',
 '6067',
 '6880',
 '69694',
 '7481',
 '75205',
 '75230',
 '78620',
 '7901',
 '80123',
 '8075',
 '85588',
 '88101',
 '90266',
 '92078',
 '93312',
 '969',
 '97204']

In [69]:
# truncating zip code down to five
df_sample['Zip'] = df_sample['Zip'].str[:5]

In [71]:
zip_bool_index = df_sample['Zip'].str.len() == 5

zip_bool_index

0        True
2        True
3        True
4        True
5        True
        ...
7228     True
7229     True
7236     True
7239     True
7244    False
Name: Zip, Length: 172, dtype: bool

In [72]:
df_sample = df_sample[zip_bool_index]

In [73]:
df_sample

,User ID,Birthdate,City,State,Zip,Available Points,Total Points Earned,Points Spent,Joined On,Last Seen
0,1,1/31/1992,Minneapolis,Georgia,55401,300,300,0,9/4/2020 0:15,12/16/2021 17:42
2,3,1/11/1990,Merida,Alabama,97204,330,330,0,10/13/2020 16:20,4/21/2021 10:54
3,4,4/16/1990,Winston-Salem,North Carolina,27106,10790,14290,3500,8/18/2020 13:21,6/30/2022 22:22
4,5,3/24/1994,Winston-Salem,North Carolina,27109,650,650,0,8/21/2020 11:27,12/30/2020 10:57
5,6,10/9/1995,G,Alabama,85588,7085,7395,310,8/18/2020 14:28,6/8/2022 23:55
...,...,...,...,...,...,...,...,...,...,...
7227,7220,8/7/1999,Winston-Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,6/26/2022 16:39
7228,7219,6/12/2004,Lutherville,Maryland,21093,490,490,0,6/22/2022 17:28,6/30/2022 8:43
7229,7220,8/7/1999,Winston-Salem,North Carolina,27106,430,430,0,6/22/2022 17:36,6/26/2022 16:39
7236,7227,3/14/2000,Clemmons,North Carolina,27012,460,460,0,6/23/2022 22:18,6/29/2022 23:40
7239,7230,5/18/1999,Winston Salem,North Carolina,27107,410,410,0,6/24/2022 16:03,6/24/2022 16:06